---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template deploys a Fluent Bit Daemonset to an ECS Cluster
Parameters:

  ecsCluster:
    Description: Please provide the ECS Cluster name that this service should run on
    Type: String

Resources:

  FluentBitService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ecsCluster
      LaunchType: EC2
      TaskDefinition: !Ref TaskDefinition
      SchedulingStrategy: DAEMON

  FluentBitTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fluentd-aggregator
      TaskRoleArn: !Ref TaskRole
      NetworkMode: host
      Volumes:
        - Name: socket
          Host:
            SourcePath: /var/run
      ContainerDefinitions:
        - Name: fluentd-daemon
          Essential: true
          Environment:
            - Name: FLB_LOG_LEVEL
              Value: INFO
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com.cn/fluent-bit:latest'
          MountPoints:
            - ContainerPath: /var/run
              SourceVolume: socket
          MemoryReservation: 50
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:  !Sub '${AWS::StackName}-daemon-fluentbit'
              awslogs-region: !Ref AWS::Region

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 14

  # This IAM Role grants the task access to firehose and CloudWatch Logs
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-fluentbit-role'
      Path: /
      AssumeRolePolicyDocument: |
          {
              "Statement": [{
                  "Sid": "",
                  "Effect": "Allow",
                  "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                  "Action": "sts:AssumeRole"
              }]
          }
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-fluentbit-policy'
          PolicyDocument:
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "firehose:PutRecordBatch"
                        ],
                        "Resource": "*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": "logs:PutLogEvents",
                        "Resource": "arn:aws:logs:*:*:log-group:*:*:*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "logs:CreateLogStream",
                            "logs:DescribeLogStreams",
                            "logs:PutLogEvents"
                        ],
                        "Resource": "arn:aws:logs:*:*:log-group:*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": "logs:CreateLogGroup",
                        "Resource": "*"
                    }
                ]
            }