
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: todo
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
      tier: experience-api-layer
  template:
    metadata:
      labels:
        app: front
        tier: experience-api-layer
    spec:
      containers:
        - name: front
          image: 530820415924.dkr.ecr.us-west-2.amazonaws.com/front:latest
          env:
            - name: STORE_SERVICE_URL
              value: http://127.0.0.1:9080


