apiVersion: v1
kind: Service
metadata:
  name: store-service
  namespace: todo
  labels:
    run: store-service
spec:
  selector:
    app: store
    tier: process-api-layer
  ports:
    - protocol: TCP
      port: 9080
